# Generated by Django 5.2.4 on 2025-08-15 21:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_post_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
    ]
